#!/usr/bin/env bun
// Generate version metadata from git and package.json.
//
// Output: src/generated/version.ts
//   - export const APP_VERSION = "1.0.0-beta";           (from package.json)
//   - export const GIT_COMMIT_HASH = "abc1234";            (short hash)
//   - export const GIT_COMMIT_DATE = "2026-09-02T08:25:11Z"; (ISO date)
//   - export const GIT_BRANCH = "main";
//   - export const BUILD_TIMESTAMP = "2026-09-02T08:25:11Z"; (when generated)
//   - export const VERSION_LABEL = "v1.0.0-beta @ abc1234";
//
// This script is idempotent and safe to run multiple times.
// In dev mode it's run as a prebuild step; in CI it should run before `next build`.

import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

// Read version from package.json
const pkgPath = path.join(process.cwd(), "package.json");
const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
const appVersion = pkg.version || "0.0.0";

// Helper: run a git command, return trimmed stdout (or fallback on error)
function git(args: string, fallback = ""): string {
  try {
    return execSync(`git ${args}`, { encoding: "utf-8", stdio: ["pipe", "pipe", "ignore"] }).trim();
  } catch {
    return fallback;
  }
}

const commitHash = git("rev-parse --short HEAD", "unknown");
const commitDate = git("log -1 --format=%cI", "");
const branch = git("rev-parse --abbrev-ref HEAD", "unknown");
const commitCount = git("rev-list --count HEAD", "0");
const isDirty = git("status --porcelain", "") !== "";

const buildTimestamp = new Date().toISOString();

// Compose a human-readable version label
// Examples:
//   v1.0.0-beta @ abc1234 (1234 commits)
//   v1.0.0-beta @ abc1234* (dirty, 1234 commits)  — * means uncommitted changes
const dirtyMarker = isDirty ? "*" : "";
const versionLabel = `v${appVersion} @ ${commitHash}${dirtyMarker}`;

// Ensure the output directory exists
const outDir = path.join(process.cwd(), "src", "generated");
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

const outPath = path.join(outDir, "version.ts");
const content = `// AUTO-GENERATED by scripts/generate-version.ts — DO NOT EDIT.
// Regenerated before every \`dev\`/\`build\` run.
//
// Source: git + package.json
// Generated at: ${buildTimestamp}

export const APP_VERSION = ${JSON.stringify(appVersion)};
export const GIT_COMMIT_HASH = ${JSON.stringify(commitHash)};
export const GIT_COMMIT_DATE = ${JSON.stringify(commitDate)};
export const GIT_BRANCH = ${JSON.stringify(branch)};
export const GIT_COMMIT_COUNT = ${JSON.stringify(Number(commitCount))};
export const BUILD_TIMESTAMP = ${JSON.stringify(buildTimestamp)};
export const IS_DIRTY = ${isDirty};
export const VERSION_LABEL = ${JSON.stringify(versionLabel)};
`;

fs.writeFileSync(outPath, content);

console.log(`✅ Version generated: ${versionLabel} (${commitCount} commits, branch: ${branch}${isDirty ? ", dirty" : ""})`);
console.log(`   Written to: ${outPath}`);
